import Head from "next/head";
import { useEffect } from "react";

const Contacts = () => {
  return (
    <>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Questa è la pagina Contatti</div>
    </>
  );
};

export default Contacts;
