import Head from "next/head";
import { useEffect } from "react";
import styles from "./About.module.scss";

const About = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Questa è la pagina About</div>
    </>
  );
};

export default About;
